# Generated by Django 5.1.4 on 2025-01-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('Morning', 'Morning'), ('Noon', 'Noon'), ('Night', 'Night')], default='Noon', max_length=20)),
                ('weather', models.CharField(choices=[('Sunny', 'Sunny'), ('Cloudy', 'Cloudy'), ('Rainy', 'Rainy')], default='Sunny', max_length=20)),
                ('season', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], default='Spring', max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('access', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
    ]
