# Generated by Django 5.1.4 on 2025-01-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='content',
        ),
    ]
