# Generated by Django 5.1.4 on 2025-01-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_remove_spot_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='season',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter'), ('All_Season', 'All Season')], default='All_Season', max_length=20),
        ),
        migrations.AlterField(
            model_name='spot',
            name='time',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Noon', 'Noon'), ('Night', 'Night'), ('All_the_Day', 'All The Day')], default='All_the_Day', max_length=20),
        ),
        migrations.AlterField(
            model_name='spot',
            name='weather',
            field=models.CharField(choices=[('Sunny', 'Sunny'), ('Cloudy', 'Cloudy'), ('Rainy', 'Rainy'), ('All_Weather', 'All Weather')], default='All_Weather', max_length=20),
        ),
    ]
