# Generated by Django 5.1.4 on 2025-01-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_spot_season_alter_spot_time_alter_spot_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='business_hours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='fees',
            field=models.TextField(blank=True, null=True),
        ),
    ]
