# Generated by Django 5.1.4 on 2025-01-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_spot_business_hours_spot_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='access',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
